name: Load Testing

on: 
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/tf.yaml

jobs:
  load-test:
    runs-on: arc-runner-set

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Choose the appropriate Java version
        distribution: 'adopt'

    - name: Setup wget and curl
      run: |
        sudo apt-get update -y
        sudo apt-get install wget -y
        sudo apt-get install curl -y

    - name: Install JMeter
      run: |
        curl https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xzf apache-jmeter-5.4.1.tgz
        export PATH=$PATH:$(pwd)/apache-jmeter-5.4.1/bin
      shell: bash

    - name: Save Installation Logs
      run: |
        mv apache-jmeter-5.4.1 /github/workspace/
      shell: bash

    - name: Upload Installation Logs
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-installation
        path: /github/workspace/apache-jmeter-5.4.1

    - name: Run JMeter Load Test
      run: |
        jmeter -n -t path/to/your/test-plan.jmx -l test-results.jtl
      working-directory: ${{ github.workspace }}

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results.jtl
